language: python
python:
  - "2.7"

notifications:
    email: false

# Setup anaconda to get scipy, and others
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda create -n testenv --yes pip python=2.7
  - conda update conda --yes
  - source activate testenv
  - conda install --yes --file requirements.txt
  - pip install .

# command to run tests
script: py.test pacpy/tests
